# Generated by Django 4.2.2 on 2023-07-02 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=25)),
                ('p_phone', models.CharField(max_length=30)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField()),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.department')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.doctors')),
            ],
        ),
    ]
