# Generated by Django 4.2.2 on 2023-07-03 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_booking2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.department')),
                ('NAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pappu', to='newapp.doctors')),
                ('SPEC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinki', to='newapp.doctors')),
            ],
        ),
    ]
