# Generated by Django 4.2.2 on 2023-07-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_register_alter_booking_booked_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking2',
            name='booking_date',
        ),
    ]
