# Generated by Django 4.2.2 on 2023-07-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_remove_booking2_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
    ]
