# Generated by Django 4.2.2 on 2023-07-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_remove_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking2',
            name='booked_on',
            field=models.DateField(auto_now=True),
        ),
    ]
