# Generated by Django 4.2.2 on 2023-07-22 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_booking_booked_to_alter_booking2_booked_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_to',
        ),
        migrations.CreateModel(
            name='ConsultationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOOKED_TO', models.DateField(null=True)),
                ('CONSULTANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.booking')),
                ('CONSULTEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplename', to='newapp.booking')),
            ],
        ),
    ]
