# Generated by Django 4.2.2 on 2023-07-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_remove_booking_booked_to_consultationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking2',
            name='booked_to',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='ConsultationData',
        ),
    ]
