# Generated by Django 4.2.2 on 2023-07-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_booking2_booked_to_delete_consultationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_to',
            field=models.DateField(null=True),
        ),
    ]
