# Generated by Django 4.2.2 on 2023-07-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_alter_booking2_booked_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_to',
            field=models.DateTimeField(null=True),
        ),
    ]
